#!/usr/bin/env python
"""Generate the TrainingJob CRD from spec/jobspec.v1alpha1.schema.json so the two cannot drift.

    python deploy/gen_crd.py           # write deploy/helm/tinyforge/crds/trainingjobs.tinyforge.dev.yaml
    python deploy/gen_crd.py --check   # exit 1 if the file on disk differs from a fresh generation

Only .spec is derived from the JobSpec schema; .status is defined here (it is written by the controller, not the user).
Any JSON Schema keyword this converter does not know raises an error instead of being silently dropped.

Constraints that Kubernetes structural schemas cannot express, and how each is handled:
  * additionalProperties: false  -> not allowed in a CRD. Unknown fields are pruned by the API server, and kubectl's
                                    default strict field validation (--validate=strict) rejects them client-visibly.
  * const                        -> enum with a single value.
  * numeric exclusiveMinimum     -> OpenAPI 3.0 form: minimum + exclusiveMinimum: true.
  * uniqueItems: true            -> x-kubernetes-list-type: set (scalar arrays only).
  * metadata.name pattern        -> CEL rule on the root object (Kubernetes only enforces DNS-1123 subdomain, 253 chars).
  * defaults on nested objects   -> Kubernetes only defaults children when the parent exists, so optional parents that
                                    contain defaults get `default: {}`.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
SCHEMA = ROOT / "spec" / "jobspec.v1alpha1.schema.json"
OUT = ROOT / "deploy" / "helm" / "tinyforge" / "crds" / "trainingjobs.tinyforge.dev.yaml"

HEADER = (
    "# GENERATED by deploy/gen_crd.py from spec/jobspec.v1alpha1.schema.json. Do not edit by hand;\n"
    "# run `python deploy/gen_crd.py` and commit the result. CI/verify runs `--check` to catch drift.\n"
)

COPY = {"type", "enum", "pattern", "minimum", "maximum", "minLength", "maxLength", "required", "default", "description"}
SKIP = {"$schema", "$id", "title"}


def convert(node: dict, path: str = "spec") -> dict:
    out: dict = {}
    for key, val in node.items():
        if key in SKIP:
            continue
        if key in COPY:
            out[key] = val
        elif key == "const":
            out["enum"] = [val]
        elif key == "exclusiveMinimum":
            out["minimum"] = val
            out["exclusiveMinimum"] = True
        elif key == "additionalProperties":
            if val is False:
                continue  # see module docstring
            out[key] = convert(val, f"{path}.additionalProperties")
        elif key == "uniqueItems":
            pass  # handled after the loop, once the item type is known
        elif key == "properties":
            props = {name: convert(sub, f"{path}.{name}") for name, sub in val.items()}
            required = set(node.get("required", []))
            for name, sub in props.items():
                has_defaulted_child = any("default" in c for c in sub.get("properties", {}).values())
                if sub.get("type") == "object" and has_defaulted_child and name not in required \
                        and "default" not in sub:
                    sub["default"] = {}
            out[key] = props
        elif key == "items":
            out[key] = convert(val, f"{path}[]")
        else:
            raise ValueError(f"{path}: unsupported JSON Schema keyword {key!r}; teach deploy/gen_crd.py about it")

    # Structural schemas require an explicit type on every node; infer it where the JSON Schema left it implicit.
    if "type" not in out:
        out["type"] = _infer_type(out, path)
    if node.get("uniqueItems"):
        if out.get("type") != "array" or out.get("items", {}).get("type") not in SCALARS:
            raise ValueError(f"{path}: uniqueItems on non-scalar items cannot be expressed as a set")
        out["x-kubernetes-list-type"] = "set"
    return out


SCALARS = ("string", "integer", "number", "boolean")


def _infer_type(out: dict, path: str) -> str:
    values = out.get("enum")
    if values:
        kinds = {"boolean" if isinstance(v, bool) else "integer" if isinstance(v, int) else
                 "number" if isinstance(v, float) else "string" if isinstance(v, str) else "?" for v in values}
        if len(kinds) == 1 and "?" not in kinds:
            return kinds.pop()
    if "properties" in out:
        return "object"
    if "items" in out:
        return "array"
    raise ValueError(f"{path}: cannot infer a type; add one to spec/jobspec.v1alpha1.schema.json")


def status_schema() -> dict:
    return {
        "type": "object",
        "description": "Observed state, written by the controller.",
        "properties": {
            "phase": {"type": "string", "enum": ["Pending", "Queued", "Running", "Succeeded", "Failed", "Interrupted"]},
            "observedGeneration": {"type": "integer", "format": "int64"},
            "startTime": {"type": "string", "format": "date-time"},
            "completionTime": {"type": "string", "format": "date-time"},
            "message": {"type": "string"},
            "conditions": {
                "type": "array",
                "x-kubernetes-list-type": "map",
                "x-kubernetes-list-map-keys": ["type"],
                "items": {
                    "type": "object",
                    "required": ["type", "status"],
                    "properties": {
                        "type": {"type": "string"},
                        "status": {"type": "string", "enum": ["True", "False", "Unknown"]},
                        "reason": {"type": "string"},
                        "message": {"type": "string"},
                        "lastTransitionTime": {"type": "string", "format": "date-time"},
                    },
                },
            },
        },
    }


def build() -> dict:
    schema = json.loads(SCHEMA.read_text(encoding="utf-8"))
    spec = convert(schema["properties"]["spec"])
    spec["description"] = "Desired training job. Generated from spec/jobspec.v1alpha1.schema.json."
    name_re = schema["properties"]["metadata"]["properties"]["name"]["pattern"]
    return {
        "apiVersion": "apiextensions.k8s.io/v1",
        "kind": "CustomResourceDefinition",
        "metadata": {"name": "trainingjobs.tinyforge.dev"},
        "spec": {
            "group": "tinyforge.dev",
            "scope": "Namespaced",
            "names": {
                "kind": "TrainingJob",
                "listKind": "TrainingJobList",
                "plural": "trainingjobs",
                "singular": "trainingjob",
                "shortNames": ["tj"],
            },
            "versions": [{
                "name": "v1alpha1",
                "served": True,
                "storage": True,
                "subresources": {"status": {}},
                "additionalPrinterColumns": [
                    {"name": "Phase", "type": "string", "jsonPath": ".status.phase"},
                    {"name": "Method", "type": "string", "jsonPath": ".spec.method"},
                    {"name": "Model", "type": "string", "jsonPath": ".spec.model.base", "priority": 1},
                    {"name": "GPUs", "type": "integer", "jsonPath": ".spec.resources.gpus"},
                    {"name": "Age", "type": "date", "jsonPath": ".metadata.creationTimestamp"},
                ],
                "schema": {"openAPIV3Schema": {
                    "type": "object",
                    "required": ["spec"],
                    "properties": {
                        "apiVersion": {"type": "string"},
                        "kind": {"type": "string"},
                        "metadata": {"type": "object"},
                        "spec": spec,
                        "status": status_schema(),
                    },
                    "x-kubernetes-validations": [{
                        "rule": f"!has(self.metadata.name) || self.metadata.name.matches('{name_re}')",
                        "message": "metadata.name must be a DNS label of at most 63 characters (lowercase alphanumerics and '-')",
                    }],
                }},
            }],
        },
    }


def render() -> str:
    return HEADER + yaml.safe_dump(build(), sort_keys=False, width=120, default_flow_style=False)


def main(argv: list[str]) -> int:
    fresh = render()
    if "--check" in argv:
        current = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if current.replace("\r\n", "\n") != fresh:
            print(f"DRIFT: {OUT.relative_to(ROOT)} is out of date; run `python deploy/gen_crd.py`", file=sys.stderr)
            return 1
        print("CRD is up to date with spec/jobspec.v1alpha1.schema.json")
        return 0
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(fresh, encoding="utf-8", newline="\n")
    print(f"wrote {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
