"""Generate a Hugging Face style model card (README.md) from a finished fine-tune run.

Every number in the card is read from files the run already wrote (ft_config.json, eval.json, task_eval.json and the
data meta.json); nothing is typed by hand. Missing inputs are stated as missing, never filled in.
"""
from __future__ import annotations

import json
from pathlib import Path


def _load(p: Path) -> dict | None:
    return json.loads(p.read_text(encoding="utf-8")) if p.exists() else None


def _pct(x: float | None) -> str:
    return "n/a" if x is None else f"{100 * x:.1f}%"


def _ci(rates: dict, key: str) -> str:
    ci = rates.get("ci95", {}).get(key)
    return f" (95% CI {100 * ci[0]:.0f}-{100 * ci[1]:.0f}%)" if ci else ""


def render(run_dir: Path) -> str:
    cfg = _load(run_dir / "ft_config.json")
    if cfg is None:
        raise FileNotFoundError(f"{run_dir}/ft_config.json not found: not a fine-tune run directory")
    ev = _load(run_dir / "eval.json")
    task = _load(run_dir / "task_eval.json")
    meta = _load(Path(cfg["data_dir"]) / "meta.json")

    out = ["---", "library_name: peft", f"base_model: {cfg['base_model']}", "tags: [tinyforge, lora]", "---", "",
           f"# {run_dir.name}: {cfg['base_model']} fine-tuned with tinyforge", "",
           "## Model",
           f"- Base model: `{cfg['base_model']}` (revision NOT pinned in this run; record the commit hash before "
           "publishing).",
           f"- Method: LoRA r={cfg['lora_r']} alpha={cfg['lora_alpha']}, quantisation `{cfg['quant']}`, "
           f"{cfg['max_steps']} steps x {cfg['examples_per_step']} examples, lr {cfg['lr']}, seed {cfg['seed']}.",
           "- Licence: inherits the base model's and the dataset's licences. NOT verified by tinyforge: check both "
           "before redistributing.", "", "## Training data"]
    if meta:
        out += [f"- Source: `{meta['source']}`; {meta['train']} train / {meta['val']} held-out examples "
                f"({meta['raw']} raw, {meta['dropped_invalid']} invalid and {meta['dropped_duplicates']} duplicates "
                f"dropped, {meta['pii_flagged']} flagged by the PII heuristic).",
                f"- Max length {meta['max_len']} tokens; {_pct(meta['truncated_frac'])} of examples truncated."]
    else:
        out.append("- Data metadata not found (`meta.json` missing).")

    out += ["", "## Evaluation"]
    if ev:
        out += [f"- Held-out loss: {ev['val_loss_base']:.3f} (base) -> {ev['val_loss_tuned']:.3f} (tuned), "
                f"{ev['improvement_pct']:.1f}% better on {ev['val_examples']} examples.",
                f"- General-text loss change (forgetting): {ev['forgetting_pct']:+.1f}% "
                "(positive = worse on general text)."]
    if task:
        t, b = task["tuned"], max((task["base_raw_prompt"], task["base_instructed"]), key=lambda r: r["lenient_em"])
        out += ["", f"Task `{task['task']}`, n={task['n']}, greedy decoding. Baseline is the stronger of two base "
                "prompts.", "", "| metric | best base prompt | tuned |", "|---|---|---|"]
        for k in ("lenient_em", "valid", "exec_acc"):
            if k in t:
                out.append(f"| {k} | {_pct(b.get(k))}{_ci(b, k)} | {_pct(t[k])}{_ci(t, k)} |")
        out.append(f"\nGain: {task['gain_pts_lenient_em']:+.1f} points lenient exact match.")
    if not ev and not task:
        out.append("- No evaluation results found. Run `tinyforge ft eval` and `tinyforge ft task-eval`.")

    out += ["", "## Limitations",
            "- Evaluated in-distribution only (held-out split of the training dataset). No claim of general ability.",
            "- Execution accuracy uses generated tables, not the real data; it can over-credit queries that coincide "
            "on synthetic rows.",
            "- Small eval sets have wide intervals; treat differences inside the CIs as noise.",
            "", "Generated by `tinyforge ft card`."]
    return "\n".join(out) + "\n"
